language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t nattawatsongsom/stephen_docker_react -f Dockerfile.dev .

script:
  - docker run -e CI=true nattawatsongsom/stephen_docker_react npm run test